services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    restart: always
    env_file: ./compose.env
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    build: ./source
    ports:
      - "3000:3000"
    restart: always
volumes:
  dbdata:
